repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        args: []
      - id: end-of-file-fixer
        args: [--skip-empty]

  - repo: https://github.com/pre-commit/mypy-plugins
    rev: v1.19.0
    hooks:
      - id: mypy
        args:
          [
            "--ignore-missing-imports",
            "--show-error-codes",
          ]

  - repo: https://github.com/psf/black
    rev: 23.10.0
    hooks:
      - id: black
        language_version: "python"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
        args: [--skip-empty]

  - repo: https://github.com/psf/isort
    rev: 5.13.0
    hooks:
      - id: isort
        extra_arguments: ["--multi-line-trailing-comma", "--force-grid-finally"]